server:
  port: 8081


spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://localhost:3306/identity-service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9093 # Kafka cluster address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: identity-group  # tên group consumer
      auto-offset-reset: earliest      # bắt đầu từ đầu nếu chưa có offset
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    cache:
      type: redis
      redis:
        host: localhost
        port: 6379
        timeout: 60000
        #password: yourpassword

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 86400 # second 24h
  refreshable-duration: 2592000 #seconds 30 ngày
  issuer: "http://identity-service"


