server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=${app.api-prefix}/books/**
          filters:
            - StripPrefix=2

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
