server:
  port: 8082
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service

  datasource:
    url: jdbc:mysql://localhost:3306/profile-service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Để Flyway quản lý schema
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9093 # Kafka cluster address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      #      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

    cache:
      type: redis
      redis:
        host: localhost
        port: 6379
        timeout: 60000
        #password: yourpassword

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      #password: yourpassword

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG